Descargar ()
Ubicar ()
Numerar en orden alfabético ( )
Estandarizar Resolución()
Montaje ( )
EQ técnica( )
Multiband compresiòn ()
EQ estética ( )
Phase y apertura del estéreo ()
Chequeo de Mono ( )
NoRmalizar (zita-dpl1 - Fons Adriaensen , Barry's satan maximiser Steve Harris, Hard Limiter-Steve Harris)
Primera prueba ( )
Revisiòn en equipos ( )
Enviar ( )
Segunda prueba ( )
Master wav ( )
Derivados ogg, FLAC, mp3 (soundconverter)
Tags (easytag)
24/48 a 16/44 ( )
Homogenizar ( )
Montaje del CD( )
Entregar ( )
Backup ( )
Entrego Backup ( )
Archivo ( )
